version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: stream-droplets-db
    environment:
      POSTGRES_DB: stream_droplets
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stream-droplets-app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: stream_droplets
      DB_USER: postgres
      DB_PASSWORD: postgres
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
      - ./scripts:/app/scripts
    command: npm run dev

volumes:
  postgres_data: